name: GithubActionDemo
on: push
jobs:
  Premier_Job:
    name: PremierJob
    runs-on: ubuntu-latest
    steps:
      - run: echo "PremierJob"
      - run: echo "Fin."
  Second_Job:
    name: SecondJob
    runs-on: ubuntu-latest
    needs: Premier_Job 
    steps:
      - run: echo "SecondJob"
      - run: echo "Fin"
